apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-nginx-demo-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-nginx-demo-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-nginx-demo-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-nginx-demo-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-nginx-demo-sa
  namespace: getting-started
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
