apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nginx-build-demo
  namespace: tekton-nginx-demo
spec:
  workspaces:
    - name: docker-workspace
  tasks:
    - name: git-clone
      taskRef: 
        name: task-git-clone
      workspaces:
        - name: kaniko
          workspace: docker-workspace
    - name: kaniko-build
      taskRef: 
        name: task-kaniko-build
      runAfter: 
        - git-clone
      workspaces:
        - name: kaniko
          workspace: docker-workspace