apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-git-clone
spec:
  params:
    - name: git-credential-secret-name
      type: string
      description: Name of the Kubernetes secret for use with Git authentication.
    - name: git-url
      type: string
      description: Git url of the repository where the Dockerfile is stored.
    - name: git-branch
      type: string
      default: main
      description: Git branch to checkout.
  workspaces:
    - name: kaniko
      description: |
        Kaniko working folder
  steps:
    - image: alpine/git
      name: git-clone
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.git-credential-secret-name)
              key: password
      script: |
        GIT_URL=$(params.git-url)
        GIT_BRANCH=$(params.git-branch)

        if [[ "$GIT_BRANCH" == *"refs/heads/"* ]]; then
          echo "Separating $GIT_BRANCH into just branch name."
          IFS="/", read -r -a array <<< $GIT_BRANCH
          GIT_BRANCH="${array[-1]}"
          echo "New branch name is $GIT_BRANCH"
        fi


        echo "Cloning repository: $GIT_URL"
        git clone $GIT_URL $(workspaces.kaniko.path)

        if [[ $GIT_BRANCH != "main " ]]; then
          echo "Checking out branch: $GIT_BRANCH"
          cd $(workspaces.kaniko.path)
          git checkout $GIT_BRANCH
        fi

        # Print directory output for logs
        ls -lah $(workspaces.kaniko.path)
      workingDir: $(workspaces.kaniko.path)