apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-increment-image-tag
spec:
  params:
    - name: image-tag
      description: If provided, will override result of this task.
      default: ""
      type: string
  results:
    - name: image-tag
      description: Generated image tag.
  workspaces:
    - name: kaniko
      description: Kaniko working folder
  steps:
    - image: alpine/git
      name: create-image-tag
      env: []
      script: |
        PARAMS_TAG=$(params.image-tag)
        RESULTS_TAG

        if [[ $PARAMS_TAG != "" ]]; then
          echo $PARAMS_TAG | tee $(results.image-tag.path)
          echo "Using pre-provided image tag: $PARAMS_TAG"
        else
          echo "Generating image tag from git hash: $(git log -1 --pretty=%H)"
          RESULTS_TAG=$(git log -1 --pretty=%h)
          echo $RESULTS_TAG | tee $(results.image-tag.path)
          echo "Generated tag: $RESULTS_TAG"
        fi        
      workingDir: $(workspaces.kaniko.path)