apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-increment-image-tag
spec:
  params:
    - name: image-tag
      description: If provided, will override result of this task.
      default: ""
      type: string
  results:
    - name: image-tag
      description: Generated image tag.
  workspaces:
    - name: kaniko
      description: Kaniko working folder
  steps:
    - image: alpine/git
      name: create-image-tag
      env: []
      script: |
        if [[ $(params.image-tag) != "" ]]; then
          echo $(params.image-tag) | tee $(results.image-tag.path)
          echo "Using pre-provided image tag: $(cat results.image-tag.path)"
        else
          echo "Generating image tag from git hash $(git log -1 --pretty=%H)"
          git log -1 --pretty=%h | tee $(results.image-tag.path)
          echo "Generated tag: $(cat results.image-tag.path)"
        fi        
      workingDir: $(workspaces.kaniko.path)