apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-increment-image-tag
spec:
  params:
    - name: image-tag
      description: If provided, will override result of this task.
      default: ""
      type: string
  results:
    - name: image-tag
      description: Generated image tag.
  workspaces:
    - name: kaniko
      description: Kaniko working folder
  steps:
    - image: alpine/git
      name: create-image-tag
      env: []
      script: |
        if [[ $(params.image-tag) != "" ]]; then
          $(results.image-tag.path)=$(params.image-tag)
          echo "Using pre-provided image tag: $(results.image-tag.path)"
        else
          echo "Generating image tag from git hash $(git log -1 %H)"
          $(results.image-tag.path)=$(git log -1 %h)
          echo "Generated tag: $(results.image-tag.path)"
        fi        
      workingDir: $(workspaces.kaniko.path)