apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-commit
spec:
  serviceAccountName: tekton-triggers-nginx-demo-sa
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-interceptor-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.commits.map(commits, commits.modified.map(modified))"
            - name: "overlays"
              value:
                - key: "filter"
                  expression: body.commits.has['docker/']
      bindings:
        - ref: github-commit-binding
      template:
        ref: github-commit-pipeline-template
